default: &default
  adapter: postgresql
  encoding: unicode
  username: abeleon
  password: showmethecode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: espn_development


test:
  <<: *default
  database: espn_test


production:
  <<: *default
  database: espn_production
  username: espn
  password: <%= ENV['ESPN_DATABASE_PASSWORD'] %>
